# Generated by Django 2.2.10 on 2020-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
