# Generated by Django 2.2.10 on 2020-05-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0002_producto_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('carrito', models.CharField(max_length=500)),
                ('precio', models.FloatField(default=0.0)),
            ],
        ),
    ]
