# Generated by Django 2.2.10 on 2020-05-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0005_registro_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='talla',
        ),
    ]
